name: Generate Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: mityatc
          svg_out_path: dist/github-contribution-grid-snake.svg   # <-- correct output path

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist    # <-- must match where the SVG is saved
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
